### PR TITLE
Replace firewalld and iptables & etc

### PR DESCRIPTION
**Pull request by Dedi-Data**
@prajwalkoirala23 
It is ready,
Could you please test it and let me know about the result and your idea?
https://github.com/Dedi-Data/wireguard-install/blob/patch-2/wireguard-server.sh

Regards

### CODE REVIEW

**Comment by Dedi-Data** [comment]
@prajwalkoirala23 
I fixed some issues on the file and checked the script on CentOS 7, everything is OK now
Please check it on other distros and let me know about the result

**Comment by prajwalkoirala23** [comment]
> @prajwalkoirala23
> I fixed some issues on the file and checked the script on CentOS 7, everything is OK now
> Please check it on other distros and let me know about the result

hey dude i am taking a look into your script and adding a few things.

give me like 30 mins and i added a little bit more code to make sure we install firewall and everything else for them if they haven't

**Comment by prajwalkoirala23** [comment]
```
if [ "$FIREWALLD_INSTALLED" == "true" ]; then
  echo -n \
  "firewall-cmd --zone=public --remove-port=$SERVER_PORT/udp; "\
  "firewall-cmd --zone=trusted --remove-source=$PRIVATE_SUBNET_V4; "\
  "firewall-cmd --zone=trusted --remove-source=$PRIVATE_SUBNET_V6; "\
  >> $WG_CONFIG
fi
```

wtf is this for??

**Comment by prajwalkoirala23** [comment]
@Dedi-Data add me on discord `Prajwal #6951`

**Comment by Dedi-Data** [comment]
@prajwalkoirala23 
I don't have discord,
it is for postdown on server configuration file

**Comment by prajwalkoirala23** [comment]
do u have skype or something??

lets get into a call i wanna change a few more things before merging this

**Comment by Dedi-Data** [comment]
@prajwalkoirala23
We Should not install firewalld:
It blocks all user ports, We can just install iptables, I checked everywhere, is there is any firewalld, it uses it, otherwise, it uses iptables, iptables is mandatory for this script
```
  ## Install Firewall
  function install-firewall() {
    if [ "$IPTABLES_INSTALLED" = "false" ]; then
      apt-get install iptables-persistent -y
    else [ "FIREWALLD_INSTALLED" = "false" ]; then
      dnf install firewalld -y
      yum install firewalld -y
      pacman -Rs firewalld -y
    fi
  }

  ## Run Function
  install-firewall
```

**Comment by Dedi-Data** [comment]
I have Telegram: @WebSiteAdmin

**Pull request closed without merging**
