### PR TITLE
check firewalld

### PR DESCRIPTION
**Pull request by Dedi-Data**

### CODE REVIEW

**Comment by prajwalkoirala23** [comment]
instead of this wanna do this??

PostUp = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE; ip6tables -A FORWARD -i wg0 -j ACCEPT; ip6tables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE; ip6tables -D FORWARD -i wg0 -j ACCEPT; ip6tables -t nat -D POSTROUTING -o eth0 -j MASQUERADE


and remove iptables and firewalled ??

**Comment by Dedi-Data** [comment]
@prajwalkoirala23

Yes, I am developing still, Please wait for my reply, I will notify when it completed

**Comment by prajwalkoirala23** [comment]
> @prajwalkoirala23
> 
> Yes, I am developing still, Please wait for my reply, I will notify when it completed

i already did it...

https://github.com/prajwalkoirala23/wireguard-install

**Comment by Dedi-Data** [comment]
@prajwalkoirala23 
No this is not correct, We have somethings to do with iptables and firewalld,
Revert back your changes, I will update my code, After that please check my code
I will notify you when it completed

**Comment by Dedi-Data** [comment]
@prajwalkoirala23 
I will apply your new codes too, Just wait ....

**Pull request closed without merging**
