### PR TITLE
check for IPV6

### PR DESCRIPTION
**Pull request by Dedi-Data**
if we couldn't find the IPV6 so we should use IPV4 as SERVER IP ADDRESS

### CODE REVIEW

**Comment by prajwalkoirala23** [comment]
other ideas are good this is a terrible idea.

**Comment by prajwalkoirala23** [comment]
lets say the client dosent have ipv6 and the server has ipv6 than the client is fucked.

**Comment by Dedi-Data** [comment]
We are saying if there was any IPV6 on the server, Use IPV4 !

**Comment by prajwalkoirala23** [comment]
no no no if they want to connect via ipv6 there is a option for that but default is ipv4

**Comment by Dedi-Data** [comment]
You have a variable : $SERVER_HOST_V6
This variable will be empty when the script can't find any IPV6 on the server
But you ask user do you like to have IPV6 ? may be he answer Yes,
Then the server ip address will be empty !

SERVER_HOST="[$SERVER_HOST_V6]"

**Comment by prajwalkoirala23** [comment]
> You have a variable : $SERVER_HOST_V6
> This variable will be empty when the script can't find any IPV6 on the server
> But you ask user do you like to have IPV6 ? may be he answer Yes,
> Then the server ip address will be empty !
> 
> SERVER_HOST="[$SERVER_HOST_V6]"

ill test this.

**Pull request merged**
